token: "1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
bot_username: "YOUR_TELEGRAM_BOT_USERNAME"
allow_only_whitelist: true
send_source_text_as_file: true
whitelist:
  users: ['1111111111', '2222222222', '3333333333', '4444444444']
  groups: ['-999999999', '-999999998']
